[env]
TERM = "xterm-256color"

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[window]
option_as_alt = "Both"
dimensions = { columns = 120, lines = 40 }
decorations = "None"
