#!/bin/sh

if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then 
    curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then 
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

mkdir -p ~/.config/tmux
mkdir -p ~/.config/nvim

ln -i -s $(pwd)/vimrc ~/.vimrc
ln -i -s $(pwd)/XCompose ~/.XCompose
ln -i -s $(pwd)/xsessionrc ~/.xsessionrc
ln -i -s $(pwd)/gitconfig ~/.gitconfig
ln -i -s $(pwd)/bash_custom ~/.bash_custom
ln -i -s $(pwd)/config/nvim/init.lua ~/.config/nvim/
ln -i -s $(pwd)/config/tmux/tmux.conf ~/.config/tmux/
ln -i -s $(pwd)/config/user-dirs.dirs ~/.config/
