#!/bin/sh
xfconf-query -c displays -lv > $(pwd)/displays.txt
xfconf-query -c keyboard-layout -lv > $(pwd)/keyboard-layout.txt
xfconf-query -c keyboards -lv > $(pwd)/keyboards.txt
xfconf-query -c pointers -lv > $(pwd)/pointers.txt
xfconf-query -c ristretto -lv > $(pwd)/ristretto.txt
xfconf-query -c thunar -lv > $(pwd)/thunar.txt
xfconf-query -c thunar-volman -lv > $(pwd)/thunar-volman.txt
xfconf-query -c xfce4-appfinder -lv > $(pwd)/xfce4-appfinder.txt
xfconf-query -c xfce4-desktop -lv > $(pwd)/xfce4-desktop.txt
xfconf-query -c xfce4-keyboard-shortcuts -lv > $(pwd)/xfce4-keyboard-shortcuts.txt
xfconf-query -c xfce4-notifyd -lv | grep -v known > $(pwd)/xfce4-notifyd.txt
xfconf-query -c xfce4-panel -lv | grep -v known > $(pwd)/xfce4-panel.txt
xfconf-query -c xfce4-power-manager -lv > $(pwd)/xfce4-power-manager.txt
xfconf-query -c xfce4-screensaver -lv > $(pwd)/xfce4-screensaver.txt
xfconf-query -c xfce4-session -lv > $(pwd)/xfce4-session.txt
xfconf-query -c xfce4-settings-editor -lv > $(pwd)/xfce4-settings-editor.txt
xfconf-query -c xfce4-settings-manager -lv > $(pwd)/xfce4-settings-manager.txt
xfconf-query -c xfce4-taskmanager -lv > $(pwd)/xfce4-taskmanager.txt
xfconf-query -c xfce4-terminal -lv > $(pwd)/xfce4-terminal.txt
xfconf-query -c xfwm4 -lv > $(pwd)/xfwm4.txt
xfconf-query -c xsettings -lv > $(pwd)/xsettings.txt
